version: '3.1'
services:
  app:
    container_name: springboot-crud-example
    image: springboot-crud-example
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    links:
      - redisContainer
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=frad123
      - POSTGRES_USER=root
      - POSTGRES_DB=test_db

  redisContainer:
    image: redis
    ports:
      - "6379:6379"